config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get 'download_pdf', to: "pages#download_pdf"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_many :missions

  validates :company, presence: true
  validates :post, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

end

app/models/message.rb
class Message < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :experience

  validates :mission, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_technos
  validates :name, presence: true
  validates :description, presence: true
end

app/models/project_techno.rb
class ProjectTechno < ApplicationRecord
  belongs_to :project
  belongs_to :techno
end

app/models/techno.rb
class Techno < ApplicationRecord
  has_many :project_technos
  validates :techno, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(message_params)
    if @message.save
      MessageMailer.new_message(@message).deliver_now
      redirect_to root_path(anchor: "contact"), notice: "Votre message a bien été envoyé"
    else
      flash[:alert] = "Veuillez remplir les champs obligatoires"
      redirect_to root_path(anchor: "contact")
    end
  end

  private

  def message_params
    params.require(:message).permit(:last_name, :first_name, :phone_number, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def download_pdf
    send_file "#{Rails.root}/public/cv.pdf", type: "application/pdf", x_sendfile: true
  end

  def home
    @experiences = Experience.all
    @projects = Project.all
    @message = Message.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>Caroline Nguyen</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('carologo.png') %>
  </head>

  <body>


<%# Devise %>
    <%= render "partials/alert" %>
    <%= yield %>
  </body>

</html>

app/views/pages/home.html.erb
<%= render "sections/banner" %>
<%= render "sections/apropos" %>
<%= render "sections/experiences" %>
<%= render "sections/skills" %>
<%= render "sections/project" %>
<%= render "sections/contactdeux" %>

app/views/partials/_alert.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/partials/_navbar.html.erb
<header data-controller="togglemenu">

    <nav class="navbar">

        <div>
          <%= link_to root_path do %>
            <%= image_tag "caro.jpg", class: "reveal transformY" %>
          <% end %>
        </div>

        <div class="nav-links" data-togglemenu-target="links">
          <ul class="d-flex">
            <li><%= link_to "Qui suis-je ?", {anchor: "profil"}, class: "link-nav reveal-2 transformY" %></li>
            <li><%= link_to "Expériences", {anchor: "experiences"}, class:"margin-left link-nav reveal-3 transformY" %></li>
            <li><%= link_to "Compétences", {anchor: "competences"}, class:"margin-left link-nav reveal-4 transformY" %></li>
            <li><%= link_to "Projets", {anchor: "projets"}, class:"margin-left link-nav reveal-5 transformY" %></li>
            <li><%= link_to "Contact", {anchor: "contact"}, class:"margin-left link-nav reveal-6 transformY" %></li>
            <li><%= link_to "CV", download_pdf_path, class:"margin-left cv hover reveal-8 transformY" %></li>
          </ul>
        </div>

        <i class="fa-solid fa-bars menu-hamburger reveal transformY" style="color: #3dcab1;" data-action="click->togglemenu#toggle"></i>

    </nav>

</header>

app/views/partials/_navbarleft_admin.erb
<div class="width-20">
  <div class="background-green height-100vh position-fixed width-20-pourcent flex-column display-flex justify-space-around align-item-center">

    <div>
      <%= link_to edit_user_registration_path do %>
        <%= image_tag "caro.jpg", class: "avatar-large-plus avatar-bordered-white" %>
        <p class="text-center mt-3 color-blue font-size-20 bold-600 hover-white">Profil</p>
      <% end %>
    </div>

    <ul>
      <div class="flex-column display-flex align-item-center gap-20">
        <li><%= link_to "Dashboard", dashboards_path, class: "color-white font-size-20 bold-600 hover-bleu" %></li>
        <li><%= link_to "Portfolio", root_path, class: "color-white font-size-20 bold-600 hover-bleu" %></li>
        <li><%= link_to "Expériences", experiences_path, class: "color-white font-size-20 bold-600 hover-bleu" %></li>
        <li><%= link_to "Projets", projects_path, class: "color-white font-size-20 bold-600 hover-bleu" %></li>
        <li><%= link_to "Messages", messages_path, class: "color-white font-size-20 bold-600 hover-bleu" %></li>
      </div>
    </ul>

    <div>
      <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "hover-white bold-600 color-blue font-size-20" %>
    </div>

  </div>
</div>

app/views/sections/_apropos.html.erb
<div class="background-white">

  <div class="container-section padding-70">
    <div class="color-black">

      <div class="mb-5 pos-relative reveal transformY">
        <h2 class="pos-relative z-index-2">À propos</h2>
        <div class="barre-title z-index-1 size-barre position-barre-titre"></div>
      </div>

      <div class="flex-gap-40 reveal-2 transformY">
        <div id="profil">
          <p class="text-justify mt-3">
            Après avoir réalisé plusieurs sites sous Wordpress,
            je me suis découvert une véritable passion pour la création de projets web !
            En octobre 2023, j’ai donc décidé de sauter le pas et de suivre une formation intensive à
            l’école Le Wagon pour me former au développement web.
          </p>
          <p class="text-justify mt-3">
            Améliorer sans cesse l'expérience utilisateur, la conversion, tester, voir ce qui fonctionne
            et optimiser est ce qui me motive le plus. J'aime être confronté à des problèmes ou difficultés techniques, réfléchir
            aux solutions puis les résoudre.
          </p>
        </div>
        <div>
          <p class="text-justify mt-3">
            Actuellement en recherche active d'un emploi en CDI, je m’investis toujours à 100% dans mes projets pour atteindre mes objectifs.
            De nature déterminée, rigoureuse et autonome, je suis toujours prête à sortir de ma zone de confort pour acquérir de nouvelles compétences.
          </p>
          <p class="text-justify mt-3">
            En équipe, j’aime travailler sérieusement, mais je pense qu'il est important de garder une ambiance positive,
            car je suis convaincue que l'enthousiasme, la bonne humeur et la bienveillance sont essentiels
            pour une collaboration efficace au sein d'une équipe.
          </p>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="grid-card grid-temp-4fr">
  <div class="card-one card">
    <p class="font-size-30 transformY reveal-3">&#127757;</p>
    <h3 class="transformY reveal-5">Voyages</h3>
    <p class="transformY reveal-6">J'aime voyager, découvrir de nouvelles cultures et de nouvelles cuisines.</p>
  </div>

  <div class="card-two card">
    <p class="font-size-30 transformY reveal-3">🪐</p>
    <h3 class="transformY reveal-5">Astronomie</h3>
    <p class="transformY reveal-6">Passionnée d'astronomie, j'aime explorer l'espace avec mon téléscope.</p>
  </div>

  <div class="card-three card">
    <p class="font-size-30 transformY reveal-3">&#9978;</p>
    <h3 class="transformY reveal-5">Randonnées</h3>
    <p class="transformY reveal-6">Le temps d'un week-end, j'aime m'évader en montagne pour bivouaquer et m'imprégner de la nature</p>
  </div>

  <div class="card-four card">
    <p class="font-size-30 transformY reveal-3">&#127947;</p>
    <h3 class="transformY reveal-5">Sport</h3>
    <p class="transformY reveal-6">Pour canaliser mon énergie, j'aime aller à la salle de sport 3 fois par semaine.</p>
  </div>
</div>

app/views/sections/_banner.html.erb
<%= render "partials/navbar" %>

<div class="background-image">

  <div class="d-flex justify-content-end">
    <div class="barre width-950 reveal transformX-r"></div>
  </div>

  <div class="container-section height-80vh d-flex flex-column justify-content-center">
    <h1 class="font-size-20px mb-2 reveal transformY">Hello world ! Je m'apelle</h1>
    <h2 class="font-size-70px mb-3 reveal-2 transformY">Caroline Nguyen</h2>
    <h3 class="font-size-35px bold mb-5 reveal-3 transformY"><span class="color-green"><</span> Développeuse fullstack <span class="color-green">/></span></h3>
    <div>
      <%= link_to "Qui suis-je ?", {anchor: "profil"}, class: "button hover reveal-4" %>
    </div>
  </div>
  <div class="barre width-350 transform-l reveal"></div>

</div>

app/views/sections/_contact.html.erb
<div class="container-section padding-70">

  <div class="display-flex justify-content-center transformY reveal">
    <div class="mb-5 pos-relative">
      <h2 class="pos-relative z-index-2">Prenons contact ?</h2>
      <div class="barre-title z-index-1 size-barre position-barre-titre width-c left-c"></div>
    </div>
  </div>

  <div class="transformY reveal-2">
    <%= simple_form_for @message do |f| %>
      <div class="grip-form">
        <%= f.input :first_name, label: 'Prénom' %>
        <%= f.input :last_name, label: 'Nom' %>
      </div>
      <div class="grip-form" id="contact">
        <%= f.input :email, label: 'Email' %>
        <%= f.input :phone_number, label: 'Téléphone'  %>
      </div>
      <%= f.input :message, label: 'Message'  %>
      <div class="display-flex justify-content-center">
        <%= f.button :submit,"Envoyer", class: "border-none mt-4 mb-5", data: { turbo: false } %>
      </div>
    <% end %>
  </div>

  <div class="display-flex align-item-center mt-3 flex-column transformY reveal-3">
    <div>
      <%= link_to "https://github.com/carolinhng", target: "_blank" do %>
        <i class="fa-brands fa-github icone-style"></i>
      <% end %>
      <%= link_to "https://www.linkedin.com/in/caroline-nguyen-8a64aa158/", target: "_blank" do %>
        <i class="fa-brands fa-linkedin-in icone-style"></i>
      <% end %>
    </div>
    <%= mail_to "caroline.ng.pro@hotmail.com", class: "mail-to-style mt-3" %>
  </div>
    <p class="text-center mt-5 font-size-12 transformY reveal-4">© Copyright 2024 - Caroline NGUYEN.<br>Tous droits réservés.</p>


</div>
<div class="barre width-100"></div>

app/views/sections/_contactdeux.html.erb
<div class="container-section padding-70">

  <div class="display-flex justify-content-center transformY reveal">
    <div class="mb-5 pos-relative">
      <h2 class="pos-relative z-index-2">On prend contact ?</h2>
      <div class="barre-title z-index-1 size-barre position-barre-titre width-c left-c"></div>

    </div>
  </div>

  <div class="display-flex align-item-center mt-3 flex-column transformY reveal-2" id="contact">
    <%= mail_to "caroline.ng.pro@hotmail.com", "Contactez-moi par e-mail", class: "button hover mt-3 mb-5" %>
    <div class="mt-3">
      <%= link_to "https://github.com/carolinhng", target: "_blank" do %>
        <i class="fa-brands fa-github icone-style"></i>
      <% end %>
      <%= link_to "https://www.linkedin.com/in/caroline-nguyen-8a64aa158/", target: "_blank" do %>
        <i class="fa-brands fa-linkedin-in icone-style"></i>
      <% end %>
    </div>
  </div>
    <p class="text-center mt-5 font-size-12 transformY reveal-3">Site réalisé avec 	&#x1F499; par Caroline Nguyen<br>Tous droits réservés.</p>


</div>
<div class="barre width-100"></div>

app/views/sections/_experiences.html.erb
<div class="background-white">
  <div class="container-section padding-90 color-black height-800">

    <div class="mb-5 pos-relative transformY reveal">
      <h2 class="mb-5 pos-relative z-index-2">Mes expériences</h2>
      <div class="barre-title z-index-1 size-barre position-barre-titre left-e width-e"></div>
    </div>

    <div class="dis-flex transformY reveal-2"
         id="experiences"
         data-controller="expechange"
         data-expechange-default-tab-value="<%=@experiences.first.id%>">

      <div class="dis-flex-column scrolling-container-x">
        <% @experiences.each do |experience| %>

              <div class="click-off border-left"
                   id="<%=experience.id%>"
                   data-expechange-target="tabs"
                   data-action="click->expechange#select">
                  <h4><%= experience.company.capitalize %></h4>
              </div>

        <% end %>
      </div>


      <% @experiences.each do |experience| %>
        <div id="<%=experience.id%>" data-expechange-target="panels" class="transformY reveal-3">
          <h3 class="mb-3 bold color-blue"><%= experience.post.capitalize %></h3>
            <h5 class="mb-3 color-bluegreen"><%= t experience.start_date.strftime('%B') %> <%= experience.start_date.strftime('%Y') %> - <%= t experience.end_date.strftime('%B') %> <%= experience.end_date.strftime('%Y') %></h5>
              <ul class="list">
                <% experience.missions.each do |mission| %>

                  <div class="display-flex align-item-start mb-3">
                    <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
                    <li class="ps-3 margin-top-5-neg"><%= mission.mission %></li>
                  </div>

                <% end %>
              </ul>
        </div>
      <% end %>


    </div>

  </div>

  <div class="barre width-350 transform-l reveal-4"></div>

</div>

app/views/sections/_project.html.erb
<div class="background-white">
  <div class="container-section padding-70 color-black">

    <div class="display-flex justify-content-center transformY reveal">
      <div class="mb-5 pos-relative">
        <h2 class="pos-relative z-index-2 color-black" id="projets">Mes projets</h2>
        <div class="barre-title z-index-1 size-barre position-barre-titre width-p left-p"></div>
      </div>
    </div>

    <% @projects.each do |project| %>
      <div class="display-flex align-item-center transformY reveal-2 mt-4">
      <%# image %>

        <div class="img-project">
          <%= image_tag(project.image)%>
            <div class="filter">

            <%# Mobile/tablet visible en dessous de width: 800px %>
              <%= link_to project.url_link.present? ? project.url_link : project.github_link, target: "_blank" do %>
                <div class="display-flex flex-column size-100-pourcent padding justify-content-center none">
                  <h3 class="bold color-bluegreen mb-2"><%= project.name %></h3>
                    <p class="color-white mb-3"><%= project.description %></p>
                  <div class="display-flex flex-wrap-wrap mb-3">
                    <% project.project_technos.each do |techno| %>
                        <p class="pastille font-size-12 hover mb-2"><%= techno.techno.techno %></p>
                    <% end %>
                  </div>
                  <div class="display-flex mt-2-neg">
                    <%= link_to project.github_link, target: "_blank" do %>
                      <i class="fa-brands fa-github icone-size"></i>
                    <% end %>
                    <% if project.url_link.present? %>
                      <%= link_to project.url_link, target: "_blank" do %>
                        <i class="fa-solid fa-square-arrow-up-right icone-size"></i>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
        </div>


      <%# Ordi visible au dessus de width 800px %>
      <%# block_right %>

      <%= link_to project.url_link.present? ? project.url_link : project.github_link, target: "_blank" do %>

        <div class="display-flex flex-column justify-content-center align-item-end absolute mobile-none transformY reveal-2">
          <h3 class="bold color-bluegreen text-end"><%= project.name %></h3>
            <div class="rect-bleu">
              <p><%= project.description %></p>
            </div>
          <div class="display-flex flex-wrap-wrap justify-content-flex-end mb-3">
            <% project.project_technos.each do |techno| %>
                <p class="pastille font-size-12 hover mb-2"><%= techno.techno.techno %></p>
            <% end %>
          </div>

          <div class="display-flex mt-2-neg">
            <%= link_to project.github_link, target: "_blank" do %>
              <i class="fa-brands fa-github icone-size"></i>
            <% end %>
            <% if project.url_link.present? %>
              <%= link_to project.url_link, target: "_blank" do %>
                <i class="fa-solid fa-square-arrow-up-right icone-size"></i>
              <% end %>
            <% end %>
          </div>
        </div>

      <% end %>
      </div>



    <% end %>

  </div>

  <div class="barre width-350 transform-l reveal-3"></div>

</div>



<%# <%= link_to project.url_link.present? ? project.url_link : project.github_link, target: "_blank" do %>

app/views/sections/_skills.html.erb
<div class="container-section padding-70">

  <div class="display-flex justify-content-center transformY reveal">
    <div class="mb-5 pos-relative">
      <h2 class="pos-relative z-index-2">Mes compétences</h2>
      <div class="barre-title z-index-1 size-barre position-barre-titre width-s left-s"></div>
    </div>
  </div>


  <div class="display-flex justify-space-between display-block transformY reveal-2" id="competences">

    <div>
      <ul class="list">
        <div class="display-flex align-item-center mb-3">
          <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
          <li class="ps-3">Conception et développement d'applications et de sites web.</li>
        </div>

        <div class="display-flex align-item-center mb-3">
          <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
          <li class="ps-3">Réalisation de projets en équipe.</li>
        </div>

        <div class="display-flex align-item-center mb-3">
          <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
          <li class="ps-3">Programmation orientée objet.</li>
        </div>

        <div class="display-flex align-item-center mb-3">
          <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
          <li class="ps-3">Conception d’une base de données relationnelle.</li>
        </div>

        <div class="display-flex align-item-center mb-3">
          <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
          <li class="ps-3">Extraction de données via APIs.</li>
        </div>

        <div class="display-flex align-item-center mb-3">
          <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
          <li class="ps-3">Coder et déployer une application en production.</li>
        </div>

        <div class="display-flex align-item-center mb-3">
          <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
          <li class="ps-3">Utilisation du design patterns MVC.</li>
        </div>

        <div class="display-flex align-item-center mb-3 padding-bot-30">
          <i class="fa-solid fa-caret-right" style="color: #3dcab1;"></i>
          <li class="ps-3">Création de site e-commerce et vitrine avec Wordpress et Woocommerce.</li>
        </div>

      </ul>
    </div>

    <div class="width-45-pourcent">
      <h4 class="text-align-mobile">Les technologies avec lesquelles j’ai travaillé :</h4>

      <div class="display-flex flex-wrap-wrap mt-4">

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3 mt-3">
          <%= image_tag "html.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px padding-left-5px">HTML</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "css.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">CSS</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "bootstrap.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Bootstrap</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "js.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Javascript</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "stimulus.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">StimulusJS</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "ruby.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Ruby On Rails</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "Postgresql.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">PostgreSQL</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "heroku.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Heroku</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "git.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Git</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "github.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Github</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "wordpress.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Wordpress</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "woocommerce.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Woocommerce</p>
        </div>

        <div class="pastille hover display-flex align-item-center gap-3-t mt-3">
          <%= image_tag "figma.png", class: "img-size" %>
          <p class="font-size-14 padding-left-5px">Figma</p>
        </div>

      </div>
    </div>


  </div>


</div>
<div class="barre width-350 transform-l reveal-3"></div>